Rails.application.config.assets.precompile += %w( chart.js )
Rails.application.config.assets.precompile += %w( targets.js )
Rails.application.config.assets.precompile += %w( appliances.js )
Rails.application.config.assets.precompile += %w( underscore.js )
Rails.application.config.assets.precompile += %w( 'http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' )
